//
//  ReactShareViewController.swift
//  RNShareMenu
//
//  DO NOT EDIT THIS FILE. IT WILL BE OVERRIDEN BY NPM OR YARN.
//
//  Created by Gustavo Parreira on 29/07/2020.
//  Updated for React Native New Architecture (0.83+)
//

import UIKit
import React
import React_RCTAppDelegate
import ReactAppDependencyProvider
import RNShareMenu

class ReactShareViewController: ShareViewController, ReactShareViewDelegate {
  var reactNativeDelegate: ShareExtensionReactNativeDelegate?
  var reactNativeFactory: RCTReactNativeFactory?
  var reactNativeWindow: UIWindow?

  override func viewDidLoad() {
    super.viewDidLoad()

    let delegate = ShareExtensionReactNativeDelegate()
    let factory = RCTReactNativeFactory(delegate: delegate)
    delegate.dependencyProvider = RCTAppDependencyProvider()

    reactNativeDelegate = delegate
    reactNativeFactory = factory

    // Create a window for the React Native view
    reactNativeWindow = UIWindow(frame: self.view.bounds)
    reactNativeWindow?.autoresizingMask = [.flexibleWidth, .flexibleHeight]

    factory.startReactNative(
      withModuleName: "ShareMenuModuleComponent",
      in: reactNativeWindow,
      launchOptions: nil
    )

    // Add the React Native window as a subview
    if let rootView = reactNativeWindow {
      rootView.backgroundColor = UIColor(red: 1, green: 1, blue: 1, alpha: 1)
      
      // Handle background color configuration
      backgroundColorSetup: if let backgroundColorConfig = Bundle.main.infoDictionary?[REACT_SHARE_VIEW_BACKGROUND_COLOR_KEY] as? [String:Any] {
        if let transparent = backgroundColorConfig[COLOR_TRANSPARENT_KEY] as? Bool, transparent {
          rootView.backgroundColor = nil
          break backgroundColorSetup
        }

        let red = backgroundColorConfig[COLOR_RED_KEY] as? Float ?? 1
        let green = backgroundColorConfig[COLOR_GREEN_KEY] as? Float ?? 1
        let blue = backgroundColorConfig[COLOR_BLUE_KEY] as? Float ?? 1
        let alpha = backgroundColorConfig[COLOR_ALPHA_KEY] as? Float ?? 1

        rootView.backgroundColor = UIColor(red: CGFloat(red), green: CGFloat(green), blue: CGFloat(blue), alpha: CGFloat(alpha))
      }
      
      self.view.addSubview(rootView)
    }

    ShareMenuReactView.attachViewDelegate(self)
  }

  override func viewDidDisappear(_ animated: Bool) {
    super.viewDidDisappear(animated)
    cancel()
    ShareMenuReactView.detachViewDelegate()
  }

  func loadExtensionContext() -> NSExtensionContext? {
    return extensionContext
  }

  func openApp() {
    self.openHostApp()
  }

  func continueInApp(with items: [NSExtensionItem], and extraData: [String:Any]?) {
    handlePost(items, extraData: extraData)
  }
}

// Custom delegate for the Share Extension
class ShareExtensionReactNativeDelegate: RCTDefaultReactNativeFactoryDelegate {
  override func sourceURL(for bridge: RCTBridge) -> URL? {
    self.bundleURL()
  }

  override func bundleURL() -> URL? {
#if DEBUG
    RCTBundleURLProvider.sharedSettings().jsBundleURL(forBundleRoot: "index.share")
#else
    let url = Bundle.main.url(forResource: "index.share", withExtension: "jsbundle")
    print("🔍 JS bundle URL in release mode: \(String(describing: url))")
    return url
#endif
  }
}
